apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka
  namespace: nju10
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
      - image: harbor.edu.cn/nju10/eureka:{VERSION}
        name: eureka-service
        ports: 
        - containerPort: 8085

---

apiVersion: v1
kind: Service
metadata:
  name: eureka-service
  namespace: nju10
spec:
  type: NodePort
  selector:
    app: eureka
  ports:
  - nodePort: 30888 # host's port，这个还有一个范围限制，只能在这之间30000-32767
    port: 8085      # service's port
    targetPort: 8085  # target pod's port