apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
  namespace: nju10
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
      - image: harbor.edu.cn/nju10/admin:{VERSION}
        name: admin-service
        ports: 
        - containerPort: 8090

---

apiVersion: v1
kind: Service
metadata:
  name: admin-service
  namespace: nju10
spec:
  type: NodePort
  selector:
    app: admin
  ports:
  - nodePort: 30890 # host's port，这个还有一个范围限制，只能在这之间30000-32767
    port: 8090      # service's port
    targetPort: 8090  # target pod's port