apiVersion: apps/v1
kind: Deployment
metadata:
  name: player
  namespace: nju10
spec:
  replicas: 3
  selector:
    matchLabels:
      app: player
  template:
    metadata:
      labels:
        app: player
    spec:
      containers:
      - image: harbor.edu.cn/nju10/player1:{VERSION}
        name: player-service
        ports: 
        - containerPort: 8083

---

apiVersion: v1
kind: Service
metadata:
  name: player-service
  namespace: nju10
spec:
  type: NodePort
  selector:
    app: player
  ports:
  - nodePort: 30881 # host's port，这个还有一个范围限制，只能在这之间30000-32767
    port: 8083    # service's port
    targetPort: 8083  # target pod's port