spring:
  application:
    name: player-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.14.220.67:3306/cloud?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: root

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8085/eureka/
  instance:
    prefer-ip-address: false


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: edu.nju.userservice.model
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8082


